name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.2
        with:
          babashka-version: 1.3.186

      - name: Run tests
        run: |
          bb -f test-runner.clj
